# Generated by Django 4.2.10 on 2024-02-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subordinate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchInstruction',
            fields=[
                ('dil_id', models.AutoField(primary_key=True, serialize=False)),
                ('dil_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dil_date', models.DateField(auto_now=True)),
                ('so_no', models.CharField(blank=True, max_length=20, null=True)),
                ('po_no', models.CharField(blank=True, max_length=20, null=True)),
                ('po_date', models.DateField(auto_now=True)),
                ('ship_to', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_to', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('ld', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_tcs_gc', models.CharField(blank=True, max_length=100, null=True)),
                ('advance_packing', models.CharField(blank=True, max_length=100, null=True)),
                ('specific_transport_instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('di_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_contact_details', models.TextField(blank=True, null=True)),
                ('partial_shipment', models.CharField(blank=True, max_length=100, null=True)),
                ('if_partial_billable', models.CharField(blank=True, max_length=100, null=True)),
                ('any_other_special_instruction', models.TextField(blank=True, null=True)),
                ('opd_or_ppmg_engineer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_engineer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ld_applicable', models.CharField(blank=True, max_length=100, null=True)),
                ('cdd', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_date', models.DateField(auto_now=True)),
                ('finance_by', models.CharField(blank=True, max_length=100, null=True)),
                ('finance_date', models.DateField(auto_now=True)),
                ('pqa_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pqa_date', models.DateField(auto_now=True)),
                ('current_level', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_level', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(auto_now=True)),
                ('dil_status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dil_status', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledge_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledge_date', models.DateField(auto_now=True)),
                ('packed_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_date', models.DateField(auto_now=True)),
                ('loaded_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('loaded_date', models.DateField(auto_now=True)),
                ('dispatched_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_date', models.DateField(auto_now=True)),
                ('revision_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.deliveryterms')),
                ('export_packing_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.exportpackingrequirement')),
                ('freight_basis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.freightbasis')),
                ('insurance_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.insurancescope')),
                ('mode_of_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.modeofshipment')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.paymentstatus')),
                ('special_gst_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.specialgstrate')),
                ('special_packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subordinate.specialpacking')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DispatchInstruction',
            },
        ),
    ]
