# Generated by Django 4.2.10 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchinstructionbilldetails',
            old_name='lingage_no',
            new_name='linkage_no',
        ),
        migrations.AlterField(
            model_name='dispatchinstructionbilldetails',
            name='revision_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchinstructionbilldetails',
            name='revision_flag',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
