# Generated by Django 4.2.10 on 2024-02-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subordinate', '0001_initial'),
        ('dispatchInstruct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchinstruction',
            name='export_packing_requirement',
        ),
        migrations.AddField(
            model_name='dispatchinstruction',
            name='export_packing_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.exportpackingrequirement'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='delivery_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.deliveryterms'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='freight_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.freightbasis'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='insurance_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.insurancescope'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='mode_of_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.modeofshipment'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='special_gst_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.specialgstrate'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='special_packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subordinate.specialpacking'),
        ),
        migrations.AlterField(
            model_name='dispatchinstruction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DispatchInstructionBillDetails',
            fields=[
                ('di_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_description', models.CharField(blank=True, max_length=100, null=True)),
                ('material_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_code', models.CharField(blank=True, max_length=100, null=True)),
                ('s_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_line_item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lingage_no', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_quantity', models.IntegerField(blank=True, null=True)),
                ('revision_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_count', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.dispatchinstruction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DispatchInstructionBillDetails',
            },
        ),
    ]
