# Generated by Django 4.2.10 on 2024-03-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dispatchbilldetails',
            table='DispatchBillDetails',
        ),
    ]
