# Generated by Django 4.2.10 on 2024-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='approved_flag',
            field=models.BooleanField(default=False),
        ),
    ]
