# Generated by Django 4.2.10 on 2024-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0002_rename_lingage_no_dispatchinstructionbilldetails_linkage_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteritemlist',
            old_name='lingage_no',
            new_name='linkage_no',
        ),
        migrations.AlterField(
            model_name='masteritemlist',
            name='revision_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='masteritemlist',
            name='revision_flag',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='masteritemlist',
            name='serial_flag',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
