# Generated by Django 4.2.10 on 2024-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0002_dispatchinstruction_approved_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchinstruction',
            name='wf_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
