# Generated by Django 4.2.10 on 2024-02-26 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatchInstruct', '0002_remove_dispatchinstruction_export_packing_requirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterItemList',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_description', models.CharField(blank=True, max_length=100, null=True)),
                ('material_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_code', models.CharField(blank=True, max_length=100, null=True)),
                ('s_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('bin', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.CharField(blank=True, max_length=100, null=True)),
                ('lingage_no', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('match_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_no', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_po_sl_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_po_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_quantity', models.IntegerField(blank=True, null=True)),
                ('revision_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_count', models.IntegerField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateField(auto_now=True)),
                ('packed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_at', models.DateField(auto_now=True)),
                ('serial_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.dispatchinstruction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MasterItemList',
            },
        ),
        migrations.CreateModel(
            name='InlineItemList',
            fields=[
                ('inline_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_no', models.CharField(blank=True, max_length=100, null=True)),
                ('accessory', models.CharField(blank=True, max_length=100, null=True)),
                ('other_info', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.masteritemlist')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InlineItemList',
            },
        ),
    ]
