# Generated by Django 4.2.10 on 2024-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0002_alter_dispatchbilldetails_revision_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dauserrequestallocation',
            name='approver_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dauserrequestallocation',
            name='approver_stage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dauserrequestallocation',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dispatchinstruction',
            name='dil_stage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
