# Generated by Django 4.2.10 on 2024-03-05 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchInstruct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowDAApproval',
            fields=[
                ('wfd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('approver', models.CharField(max_length=150, null=True)),
                ('level', models.IntegerField(null=True)),
                ('parallel', models.BooleanField(null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.dispatchinstruction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowtype')),
            ],
            options={
                'db_table': 'WorkFlowDAApproval',
            },
        ),
        migrations.CreateModel(
            name='DAUserRequestAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('approve_status', models.CharField(default='Approver', max_length=200)),
                ('approver_flag', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.dispatchinstruction')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DAUserRequestAllocation',
            },
        ),
        migrations.CreateModel(
            name='DaAuthThreads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_list', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatchInstruct.dispatchinstruction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DaAuthThreads',
            },
        ),
    ]
