# Generated by Django 4.2.10 on 2024-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdaapprovers',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
