# Generated by Django 4.2.10 on 2024-03-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowaccess',
            name='dept_code',
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department', to='accounts.subdepartment'),
        ),
    ]
