# Generated by Django 4.2.10 on 2024-03-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflow', '0002_remove_workflowaccess_dept_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaccess',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subdepartment'),
        ),
        migrations.AlterField(
            model_name='workflowaccess',
            name='wf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowtype'),
        ),
    ]
