# Generated by Django 4.2.10 on 2024-03-21 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0003_alter_workflowaccess_sub_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowemployees',
            name='wfc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowcontrol'),
        ),
        migrations.CreateModel(
            name='WorkFlowDeptEmp',
            fields=[
                ('wfde_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wfa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowaccess')),
            ],
            options={
                'db_table': 'WorkflowDeptEmp',
            },
        ),
    ]
