# Generated by Django 4.2.10 on 2024-03-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflowemployees_wfc_id_workflowdeptemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowaccess',
            old_name='sub_department',
            new_name='job_code',
        ),
    ]
