# Generated by Django 4.2.10 on 2024-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_rename_sub_department_workflowaccess_job_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowaccess',
            old_name='job_code',
            new_name='dept_code',
        ),
    ]
