# Generated by Django 4.2.10 on 2024-03-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_rename_job_code_workflowaccess_dept_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcontrol',
            name='wf_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfc', to='workflow.workflowtype'),
        ),
        migrations.AlterField(
            model_name='workflowemployees',
            name='wfc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfe', to='workflow.workflowcontrol'),
        ),
    ]
