dil_upload_columns = ['Reference Document', 'Sold-to Party', 'Sold-to Party Name', 'Delivery',
                      'Delivery Create Date', 'Delivery Item', 'Tax Invoice Number (ODN)',
                      'Reference Document Item', 'MS Code', 'Quantity (Sales)',
                      'Linkage Number', 'Sales Office', 'Terms of Payment',
                      'Tax Invoice Date', 'Material Description', 'Plant', 'Plant Name',
                      'Unit (Sales)', 'Billing Number', 'Billing Create Date',
                      'Currency (Sales)', 'Ship-to party', 'Ship-to Party Name',
                      'Ship-to Country', 'Ship-to Postal Code', 'Ship-to City',
                      'Ship-to Street', 'Ship-to Street4', 'Insurance Scope',
                      'Sold-to Country', 'Sold-to Postal Code', 'Sold-to City',
                      'Sold-to Street', 'Sold-to Street4', 'Material Number', 'HS Code',
                      'HS Code Export', 'Delivery quantity', 'Unit (Delivery)',
                      'Storage Location', 'DIL Output Date', 'Sales Document Type',
                      'Distribution Channel', 'Invoice Item', 'Tax Invoice Assessable Value',
                      'Tax Invoice Total Tax Value', 'Tax Invoice Total Value',
                      'Item Price (Sales)', 'Packing status', 'DO Item Packed Quantity',
                      'Packed Quantity unit']
